Only build PRs that target main
googlefonts/googlesans-flex pull request #919
Opened 2024-04-03 16:07 UTC by Hoolean

Update(Ricky): changed approach to check if a PR is targetting `main`

---

This PR stops our automatic build workflow from running for PRs that only change the sources within `sources/design-source/`.

Changes in this folder do not affect the UFO sources or pipeline until manually imported, and so have no effect on the final TTFs.

## Workflows

This would avoid booting the CI for these recent builds (highlighted):

![List of recent build workflows, with those that would no longer be issued highlighted](https://github.com/googlefonts/googlesans-flex/assets/2150762/62caaf2e-a73e-40b9-a627-4dc789a57e4c)

## Future

If we find that CI feedback for Glyphs PRs would be helpful, we could reinstate automated builds but with the "Build from Glyphs package" workflow instead, depending on CI minutes available 🚀

2024-04-03 16:09 UTC, Hoolean commented
After this is merged we can make a test PR changing only the Glyphs sources to confirm that a build job is no longer started; if it sneaks through anyway, we can cancel it on the spot and try a different approach 💥

2024-04-03 16:28 UTC, Hoolean commented
Extra note: if this commit works, we might need to cherry pick it into the branches where design work is happening :)

2024-04-04 09:14 UTC, RickyDaMa requested changes

2024-04-04 09:14 UTC, RickyDaMa commented on .github/workflows/build.yaml
> +      - 'sources/design-source/**'
From my experience, this won't work due to how many files there are in the Flex repo :(

Might need to go for a naming convention approach for branches we want to exclude

2024-04-05 10:05 UTC, RickyDaMa approved these changes

2024-04-05 14:13 UTC, merged